#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    exit 1;
)

# Check ESLint Standards
npm run lint ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    exit 1;
)

# Check TypeScript Errors
npm run type-check ||
(
    echo 'TypeScript Check Failed. Fix the errors above and try to commit again.';
    exit 1;
)

echo '✅✅✅✅ Success  ✅✅✅✅'
 